jwt:
    secret: ${JWT_SECRET_KEY}
spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
        generate-ddl: true
    application:
        name: chaea
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 82296007466-9a641tum32kufd180hg7p9nol7dcsglg.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile, email
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://www.googleapis.com/oauth2/v4/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: sub
            resourceserver:
                jwt:
                      issuer-uri: https://accounts.google.com
                      jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /docs/swagger-ui.html
        
server:
  port: 8091
